import { Button, Layout, Input, Form, Typography, Alert } from 'antd'
// import Form from 'antd/lib/form'
// import Input from 'antd/lib/input'
// import {  } from 'antd'
import { Content, Footer, Header } from 'antd/lib/layout/layout'
import Space from 'antd/lib/space'
import axios, { AxiosError } from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const { Title } = Typography;
type LinkType = {
  link: string,
}
type ResponseError = {
  ok: boolean,
  status: number,
  message: string | any
}
const Home: NextPage = () => {
  const [status, setStatus] = useState<'error' | 'success' | 'initial'>('initial');
  const [message, setMessage] = useState<string>('');
  const [form] = Form.useForm();
  // const url = Form.useWatch('url', form);

  const handleWrongOnSubmit = () => {
    setStatus(prev => 'error');
    setMessage(prev => form.getFieldError('url').join(' '))
    // console.log(form.getFieldError('url').join(' '))
  }

  const submitHandler = async (Link: LinkType) => {
    try {
      const req = await axios.post('/api/addUrl', {
        ...Link
      })
      setStatus(prev => 'success');
      setMessage(prev => 'http://localhost:3000/' + req?.data?.url?.key)
    } catch (e: any) {
      const error = e as AxiosError<ResponseError>
      setStatus(prev => 'error');
      setMessage(error?.response?.data?.message || 'internal error')
    }
  }

  // const trace = (e: any) => {
  //   console.log(url)
  //   console.log(form.getFieldError('url').join(''))
  //   console.log(e.target.value)
  //   console.log(form.getFieldValue('url'))
  // }
  return (
    <Layout className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className={styles.logo} >
          <h1 className={styles.title}>URL Shortener</h1>
        </div>
      </Header>
      <Content className={styles.content}>
        <div className={styles.shorten}>
          <Title level={5}>Enter your URL</Title>
          <Form
            // name='url'
            form={form}
            // style={{ height: '100%' }}
            onFinishFailed={handleWrongOnSubmit}
            onFinish={submitHandler}
          // onChangeCapture={trace}
          // onChange={trace}
          >
            <div className={styles.form}>
              <div className={styles.formInput}>
                <Form.Item
                  noStyle
                  name="url"
                  rules={[{ required: true }
                    , { type: 'url', message: 'Please enter valid url' },
                    // { type: 'string', min: 6 },
                  ]}
                >
                  <Input
                    placeholder="Shorten your link"
                    size="large"
                  // inputMode='url'
                  />
                </Form.Item>
              </div>
              <div className={styles.formBtn}>
                <Form.Item>
                  <Button type="primary" htmlType="submit" size="large">
                    Submit
                  </Button>
                </Form.Item>
              </div>
            </div>
          </Form>
          {
            status === 'error' ||
              status === 'success' ?
              <Alert
                message={message}
                type={status}
                showIcon
              /> : null
          }
        </div>
      </Content>
      <Footer className={styles.footer}>
        Created with Next.js, NodeJS and MongoDB by Hamed Osama &copy; 2022
      </Footer>
    </Layout>
  )
}

export default Home
