import { Button, Layout, Input, Form, Typography, Alert, Skeleton } from 'antd'
import { Content, Footer, Header } from 'antd/lib/layout/layout'
import Space from 'antd/lib/space'
import axios, { AxiosError } from 'axios'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import CustomSkelton from '../components/CustomSkeleton'
import styles from '../styles/Home.module.css'

import Cookies from 'js-cookie'
import Url from '../models/url'
import connect from '../db/db'
const { Title } = Typography;
type LinkType = {
  link: string,
}
type ResponseError = {
  ok: boolean,
  status: number,
  message: string | any
}
const Home: NextPage = (props: any) => {
  const [status, setStatus] = useState<'error' | 'success' | 'initial'>('initial');
  const [message, setMessage] = useState<string>('');
  const [data, setData] = useState(props.urls ? JSON.parse(props.urls) : [])
  const [form] = Form.useForm();
  // const url = Form.useWatch('url', form);

  const handleWrongOnSubmit = () => {
    setStatus(prev => 'error');
    setMessage(prev => form.getFieldError('url').join(' '))
    // console.log(form.getFieldError('url').join(' '))
  }

  const addToCookies = (url: string) => {
    const oldData = Cookies.get('hashes')
    console.log(oldData)
    const formattedUrl = {
      hash: url
    }
    let newFormat = [];
    if (oldData) {
      newFormat = JSON.parse(oldData);
      newFormat.push(formattedUrl);
      Cookies.set('hashes', JSON.stringify(newFormat), { expires: 365 });
    }
    else {
      newFormat.push(formattedUrl)
      Cookies.set('hashes', JSON.stringify(newFormat), { expires: 365 });
    }
  }
  const submitHandler = async (Link: LinkType) => {
    try {
      const req = await axios.post('/api/addUrl', {
        ...Link
      })
      addToCookies(req?.data?.url?.key)
      setData((prev: []) => [...prev, req?.data?.url])
      setStatus(prev => 'success');
      setMessage(prev => 'http://localhost:3000/' + req?.data?.url?.key)
    } catch (e: any) {
      const error = e as AxiosError<ResponseError>
      setStatus(prev => 'error');
      setMessage(error?.response?.data?.message || 'internal error')
    }
  }

  // const trace = (e: any) => {
  //   console.log(url)
  //   console.log(form.getFieldError('url').join(''))
  //   console.log(e.target.value)
  //   console.log(form.getFieldValue('url'))
  // }
  return (
    <Layout className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className={styles.navbar}>
        <div className={styles.logo} >
          <h1 className={styles.title}>URL Shortener</h1>
        </div>
      </Header>
      <Content className={styles.content}>
        <div className={styles.shorten}>
          <Title level={5}>Enter your URL</Title>
          <Form
            // name='url'
            form={form}
            // style={{ height: '100%' }}
            onFinishFailed={handleWrongOnSubmit}
            onFinish={submitHandler}
          // onChangeCapture={trace}
          // onChange={trace}
          >
            <div className={styles.form}>
              <div className={styles.formInput}>
                <Form.Item
                  noStyle
                  name="url"
                  rules={[{ required: true }
                    , { type: 'url', message: 'Please enter valid url' },
                    // { type: 'string', min: 6 },
                  ]}
                >
                  <Input
                    placeholder="Shorten your link"
                    size="large"
                  // inputMode='url'
                  />
                </Form.Item>
              </div>
              <div className={styles.formBtn}>
                <Form.Item>
                  <Button type="primary" htmlType="submit" size="large">
                    Submit
                  </Button>
                </Form.Item>
              </div>
            </div>
          </Form>
          {
            Array(4).fill(0).map((el, i) => (
              <CustomSkelton key={i} urlData={data[i] ?? null} />
            ))
          }
          {
            status === 'error' ||
              status === 'success' ?
              <Alert
                type={status}
                showIcon
                description={
                  <a href={message} target="_blank" rel="noreferrer">{message}</a>
                }
              /> : null
          }
          {
            data.length === 4 ? <p>Maximum number of links reached.Delete existing links to add more links</p> : null
          }
        </div>
      </Content>
      <Footer className={styles.footer}>
        Created with Next.js, NodeJS and MongoDB by Hamed Osama &copy; 2022
      </Footer>
    </Layout>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context): Promise<any> => {
  const cookies = context?.req?.cookies?.hashes as string
  const hashes = cookies ? JSON.parse(cookies) : null;
  if (!hashes)
    return {
      props: {
        links: []
      }
    }
  await connect()
  const data = [];
  for (const el of hashes) {
    const url = await Url.findOne({ key: el.hash }, { __v: 0 });
    data.push(url);
  }
  return {
    props: {
      urls: JSON.stringify(data)
    }
  }
}