import { Button } from 'antd'
import Form from 'antd/lib/form'
import Input from 'antd/lib/input'
import Layout from 'antd/lib/layout'
import { Content, Footer, Header } from 'antd/lib/layout/layout'
import Space from 'antd/lib/space'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = (pp) => {
  console.log(pp)
  return (
    <Layout className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <div className={styles.logo} >
          <h1 className={styles.title}>URL Shortener</h1>
        </div>
      </Header>
      <Content className={styles.content}>
        <div className={styles.shorten}>
          <Form
            name='customized_form_controls'
            style={{ height: '100%' }}
          >
            <div className={styles.form}>
              <div className={styles.formInput}>
                <Form.Item
                  name="url"
                  rules={[{ required: true }
                    , { type: 'url', warningOnly: true, message: 'Please enter valid url' },
                  { type: 'string', min: 6 },]}
                >
                  <Input
                    placeholder="Shorten your link"
                    size="large"
                  />
                </Form.Item>
              </div>
              <div className={styles.formBtn}>
                <Form.Item>
                  <Button type="primary" htmlType="submit" size="large">
                    Submit
                  </Button>
                </Form.Item>
              </div>
            </div>
          </Form>
          {/* <Button type='primary'>Shorten</Button> */}
        </div>
      </Content>
      <Footer className={styles.footer}>
        Created with Next.js, NodeJS and MongoDB by Hamed Osama &copy; 2022
      </Footer>
    </Layout>
  )
}

export default Home
